version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: carteira-luxo-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql &&
      apache2-foreground"

  db:
    image: mysql:8.0
    container_name: carteira-luxo-db
    restart: always
    environment:
      MYSQL_DATABASE: carteira_investimentos
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carteira-luxo-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  mysql_data: 